export const LOCATION_WEATHER_DATA_REQUEST_LOAD = 'LOCATION_WEATHER_DATA_REQUEST_LOAD';
export const LOCATION_WEATHER_DATA_REQUEST_SUCCESS = 'LOCATION_WEATHER_DATA_REQUEST_SUCCESS';
export const LOCATION_WEATHER_DATA_REQUEST_ERROR = 'LOCATION_WEATHER_DATA_REQUEST_ERROR';

export const ADD_LOCATION_VALUE_UPDATE = 'ADD_LOCATION_VALUE_UPDATE';