export const API_BASE_URL = 'http://api.openweathermap.org/data/2.5/';

export const LOCATION_WEATHER_DATA_REQUEST_LOAD = 'LOCATION_WEATHER_DATA_REQUEST_LOAD';
export const LOCATION_WEATHER_DATA_REQUEST_SUCCESS = 'LOCATION_WEATHER_DATA_REQUEST_SUCCESS';
export const LOCATION_WEATHER_DATA_REQUEST_ERROR = 'LOCATION_WEATHER_DATA_REQUEST_ERROR';

export const LOCATION_FORECAST_DATA_REQUEST_LOAD = 'LOCATION_FORECAST_DATA_REQUEST_LOAD';
export const LOCATION_FORECAST_DATA_REQUEST_SUCCESS = 'LOCATION_FORECAST_DATA_REQUEST_SUCCESS';
export const LOCATION_FORECAST_DATA_REQUEST_ERROR = 'LOCATION_FORECAST_DATA_REQUEST_ERROR';

export const ADD_LOCATION_VALUE_UPDATE = 'ADD_LOCATION_VALUE_UPDATE';